### ISSUE TITLE
Masking convention is inconsistent?

### ISSUE THREAD

**Issue by gsganden** [warner-benjamin/transformer-from-scratch#4]
IIUC, `False` now indicates a masked position in exercises/attention_mechanism/attention.py and an attended position in exercises/attention_block/attention_block.py . I think the former is a recent change, so I assume it is the considered intended approach. Should we revise the latter to match?

**Comment by gsganden** [comment]
I think the reference code is still using the old convention, and not just the docstring?

**Comment by warner-benjamin** [comment]
Missed that when merging in main. Thanks. Resolved in 3e43b46.

**Comment by gsganden** [comment]
Thank you!

The reference solutions still have a few "False indicates a masked position" at least in the docstrings, e.g. at https://github.com/warner-benjamin/transformer-from-scratch/blob/main/exercises/attention_block/solution/hidden/reference_attention_block.py#L46C78-L46C111, and use that convention in the causal mask (https://github.com/warner-benjamin/transformer-from-scratch/blob/main/exercises/attention_block/solution/hidden/reference_attention_block.py#L123)

**Comment by gsganden** [comment]
Maybe it would be worthwhile to write a little script to generate exercises from solutions (replacing function bodies with `raise NotImplementedError`) to make it easy to keep them in sync? I had a system like this when I was teaching data science for General Assembly, and it was quite helpful, but maybe only worth developing if you are going to do this kind of thing frequently.

**Comment by warner-benjamin** [comment]
The causal mask is fine, as it's applied in a separate masked_fill call from the attention mask. Creating it pre-inverted saves an operation during the model's forward/backward pass.

**Comment by gsganden** [comment]
Got it. Thanks!
